# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    neikeq.clubs.player_role:
        class: Neikeq\ClubsBundle\Twig\PlayerRole
        public: false
        tags:
            - { name: twig.extension }

    neikeq.clubs.position:
        class: Neikeq\ClubsBundle\Twig\Position
        public: false
        tags:
            - { name: twig.extension }
