kicks_clubs:
    path:     /
    defaults: { _controller: NeikeqClubsBundle:Security:root }

kicks_clubs_login:
    path:     /login/
    defaults: { _controller: NeikeqClubsBundle:Security:login }

kicks_clubs_login_check:
    path:     /login_check/
    defaults: { _controller: NeikeqClubsBundle:Security:loginCheck }

kicks_clubs_logout:
    path:     /logout/
    defaults: { _controller: NeikeqClubsBundle:Security:logout }

kicks_clubs_character:
    path:     /character/
    defaults: { _controller: NeikeqClubsBundle:Clubs:character }

kicks_clubs_character_check:
    path:     /character_check/
    defaults: { _controller: NeikeqClubsBundle:Clubs:characterCheck }

kicks_clubs_clubs:
    path:     /clubs/
    defaults: { _controller: NeikeqClubsBundle:Clubs:clubs }

kicks_clubs_clubs_page:
    path:     /clubs/{page}/
    defaults: { _controller: NeikeqClubsBundle:Clubs:clubsPage }

kicks_clubs_create:
    path:     /create/
    defaults: { _controller: NeikeqClubsBundle:Creation:create }

kicks_clubs_club:
    path:     /club/
    defaults: { _controller: NeikeqClubsBundle:Clubs:club }

kicks_clubs_ajax_club_info:
    path:     /ajax/clubinfo/
    defaults: { _controller: NeikeqClubsBundle:Clubs:ajaxClubInfo }

kicks_clubs_ajax_member_info:
    path:     /ajax/memberinfo/
    defaults: { _controller: NeikeqClubsBundle:Members:ajaxMemberInfo }

kicks_clubs_member_join:
    path:     /join/
    defaults: { _controller: NeikeqClubsBundle:Members:join }

kicks_clubs_member_join_check:
    path:     /join_check/
    defaults: { _controller: NeikeqClubsBundle:Members:joinCheck }

kicks_clubs_member_request:
    path:     /request/
    defaults: { _controller: NeikeqClubsBundle:Members:request }

kicks_clubs_member_leave:
    path:     /leave/
    defaults: { _controller: NeikeqClubsBundle:Members:leave }

kicks_clubs_member_leave_check:
    path:     /leave_check/
    defaults: { _controller: NeikeqClubsBundle:Members:leaveCheck }

kicks_clubs_manager_requests:
    path:     /requests/
    defaults: { _controller: NeikeqClubsBundle:Manager:requests }

kicks_clubs_manager_information:
    path:     /information/
    defaults: { _controller: NeikeqClubsBundle:Manager:information }

kicks_clubs_manager_members:
    path:     /members/
    defaults: { _controller: NeikeqClubsBundle:Manager:members }

kicks_clubs_manager_kickout:
    path:     /kickout/
    defaults: { _controller: NeikeqClubsBundle:Manager:kickOut }

kicks_clubs_manager_advanced:
    path:     /advanced/
    defaults: { _controller: NeikeqClubsBundle:Manager:advanced }

kicks_clubs_manager_membership_update:
    path:     /membership_update/
    defaults: { _controller: NeikeqClubsBundle:Manager:membershipUpdate }

kicks_clubs_manager_remove_club:
    path:     /remove_club/
    defaults: { _controller: NeikeqClubsBundle:Manager:removeClub }
