kicks_clubs:
    path:     /
    defaults: { _controller: NeikeqClubsBundle:Security:root }

kicks_clubs_login:
    path:     /login/
    defaults: { _controller: NeikeqClubsBundle:Security:login }

kicks_clubs_login_check:
    path:     /login_check/
    defaults: { _controller: NeikeqClubsBundle:Security:loginCheck }

kicks_clubs_logout:
    path:     /logout/
    defaults: { _controller: NeikeqClubsBundle:Security:logout }

kicks_clubs_character:
    path:     /character/
    defaults: { _controller: NeikeqClubsBundle:Clubs:character }

kicks_clubs_character_check:
    path:     /character_check/
    defaults: { _controller: NeikeqClubsBundle:Clubs:characterCheck }

kicks_clubs_clubs:
    path:     /clubs/
    defaults: { _controller: NeikeqClubsBundle:Clubs:clubs }

kicks_clubs_clubs_page:
    path:     /clubs/{page}/
    defaults: { _controller: NeikeqClubsBundle:Clubs:clubsPage }

kicks_clubs_create:
    path:     /create/
    defaults: { _controller: NeikeqClubsBundle:Creation:create }

kicks_clubs_create_check:
    path:     /create_check/
    defaults: { _controller: NeikeqClubsBundle:Creation:createCheck }

kicks_clubs_club:
    path:     /club/
    defaults: { _controller: NeikeqClubsBundle:Clubs:club }

kicks_clubs_ajax_club_info:
    path:     /ajax/clubinfo/
    defaults: { _controller: NeikeqClubsBundle:Clubs:ajaxClubInfo }

kicks_clubs_join:
    path:     /join/
    defaults: { _controller: NeikeqClubsBundle:Clubs:join }

kicks_clubs_join_check:
    path:     /join_check/
    defaults: { _controller: NeikeqClubsBundle:Clubs:joinCheck }
